package:
  name: platformio-toolchain-atmelavr
  version: 1.40902.1

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - platformio

  run:
    - platformio
